version: '3'
services:
  kijiji:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: kijiji:latest
    environment:
      PRICE_MIN: 1500
      PRICE_MAX: 3000
      RADIUS: 10.0
      ADDRESS: 'M5G1P5'
      LATITUDE: 43.6534829
      LONGITUDE: -79.3862826
      DB_URL: postgres://postgres:password@db:5432/kijiji
    depends_on:
      - "db"
    command: sh -c './wait-for.sh db:5432 -- ./run.sh'
  db:
    image: postgres:10.5
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"